### ISSUE TITLE
invalid option on decrease volume

### ISSUE THREAD

**Issue by map7** [flexibeast/pulseaudio-control#1] opened 2017-10-13 04:36 UTC
I'm running Debian Jessie and when I use pulseaudio-control to decrease the volume it doesn't work and I get the following printed in my current buffer;

/usr/bin/pactl: invalid option -- '1'

**Comment by flexibeast** [comment] 2017-10-13 05:04
Could you please do `M-x toggle-debug-on-error` and try to decrease the volume? Hopefully that should give you a buffer with more detailed error information, which you can then paste here.

**Comment by map7** [comment] 2017-10-13 05:57
I'm not getting any new buffers or information when I do this

**Comment by flexibeast** [comment] 2017-10-13 06:20
Can you please run `pactl list short sinks` from the terminal and share the output?

Also, could you please report the values of the `pulseaudio-control--current-sink` and the `pulseaudio-control-volume-step` variables? You can do this by doing `C-h v` and entering the variable name.

**Comment by map7** [comment] 2017-10-15 22:01
```
$ pactl list short sinks
0	alsa_output.pci-0000_00_03.0.hdmi-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
2	alsa_output.pci-0000_00_1b.0.analog-stereo	module-alsa-card.c	s16le 2ch 48000Hz	SUSPENDED
3	alsa_output.usb-Dell_Dell_AC511_USB_SoundBar-00-SoundBar.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
```
pulseaudio-control--current-sink
`alsa_output.usb-Dell_Dell_AC511_USB_SoundBar-00-SoundBar.analog-stereo`

pulseaudio-control-volume-step
`10%`

**Comment by flexibeast** [comment] 2017-10-16 05:04
Hmm, this makes me wonder whether the issue is that the interface of `pactl` has changed between recent versions; i'm on Debian Stretch myself, and it works fine. What output do you get if you run `pactl set sink volume alsa_output.usb-Dell_Dell_AC511_USB_SoundBar-00-SoundBar.analog-stereo -10%`?

**Comment by map7** [comment] 2017-10-19 04:57
Under Debian Jessie I get the error
```
pactl set sink volume alsa_output.usb-Dell_Dell_AC511_USB_SoundBar-00-SoundBar.analog-stereo -10%
pactl: invalid option -- '1'
```

**Comment by flexibeast** [comment] 2017-10-19 08:51
Okay, does it work if you do:

    pactl -- set-sink-volume alsa_output.usb-Dell_Dell_AC511_USB_SoundBar-00-SoundBar.analog-stereo -10%

?

**Comment by map7** [comment] 2017-10-19 23:10
Yes this works

**Comment by flexibeast** [comment] 2017-10-20 06:41
Okay, i've pushed what i believe to be a fix; could you please upgrade your copy of the package and let me know if it works for you?

**Comment by flexibeast** [comment] 2018-06-26 04:47
No feedback indicating the fix isn't working, so closing this issue.

**Closed as completed by flexibeast** 2018-06-26 04:47 UTC
